In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.txt" , sep = ';' , header=None , names = ["text" , "emotion"])

In [3]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [4]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}

i = 0 
for emo in unique_emotions:
    emotion_numbers[emo] = i 
    i += 1
    
df['emotion']=df['emotion'].map(emotion_numbers)

In [5]:
df['emotion'].unique()

array([0, 1, 2, 3, 4, 5])

### text lowercasing

In [6]:
df['text'] = df['text'].apply(lambda x : x.lower())

remove punctuation

In [7]:
import string
def remove_punc(text):
    return text.translate(str.maketrans('' , '' , string.punctuation))

In [8]:
df['text'] = df['text'].apply(remove_punc)

In [9]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [10]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new+i
    return new

In [11]:
df['text'] = df['text'].apply(remove_numbers)

remove stopwords

In [12]:
import nltk
import nltk.tokenize

In [13]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [14]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /home/jatin/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/jatin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
stop_words = set(stopwords.words('english'))

In [17]:
df.loc[1].text

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [20]:
def remove(txt):
    words = txt.split()
    cleaned = []
    for i in words : 
        if not i in stop_words:
            cleaned.append(i)
    return " ".join(cleaned)

In [21]:
df['text'] = df['text'].apply(remove)

In [22]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'